### ISSUE TITLE
[DISCUSSION] Add and modify cortex to train on our dataset

### ISSUE THREAD

**Issue by ilyassakhanov** [dhk465/symbolic_comp_one#23]
# Import of a Cortex
 As for now, we don't have any files from cortex, meaning we can't combine cortex with our previous         project.
## My solution:
Put the cortex files into our project and make sure it works

**Comment by dhk465** [comment]
If you are talking about the dependency, it is already in project.clj.
Otherwise, we should not include the whole cortex clone into our project, they will conflict unless we sort the files out and trim unnecessary parts.
If we know that, we should also know how to integrate cortex in the first place.

**Comment by dhk465** [comment]
And what about the idea of using [this MXNET library](https://github.com/apache/incubator-mxnet/tree/master/contrib/clojure-package) instead of cortex?

**Comment by dhk465** [comment]
We might just use Tensorflow to make the image recognition. According to #30 we just need to find an adequate library for that.
